### ISSUE TITLE
eeprom-data.hex is a bit confusing to edit

### ISSUE THREAD

**Issue by crabdancing** [KivApple/dell-charger-emulator#2]
So, `eeprom-data.hex` isn't a binary file. I was originally confused about this -- trying to open it in a hex editor and such, before I realized it was "meta-hex" -- ASCII values encoded in hexadecimal.

This seems confusing to edit, and none of my coding tools will actually interpret the hex data into ASCII in any panels, so I can see what it says easily. E.g., where the "DELL" tag is, etc.

Now, of course, I can do all this by hand, but it doesn't seem ideal. I'm weary of making a mistake, since I could theoretically fry a motherboard that way.

Is this ASCII-encoded *.hex file a standard format? If so, what tools can I use to edit it? (PLEASE let them be FOSS tools! :stuck_out_tongue_closed_eyes:)

If _not_, would it be worth considering having this be a normal binary file instead of ASCII-encoded?

**Comment by KivApple** [comment]
Intel hex is standard format for firmware, which recognized by avrdude.
You can use my python script to change charger data.

**Comment by crabdancing** [comment]
@KivApple Ah! I will just use that, then, for this project. Thanks!

But, is there a standard tool for editing it that you know of, with features like a hex editor? Or even better a hex editor that will also except intel .hex files? I like to know how to easily do things by hand, in case I need to. :stuck_out_tongue:

Edit: for anyone coming from a search engine and wondering this: apparently there is a FOSS program to handle this format (including converting it to and from binary) called [srecord](http://srecord.sourceforge.net). It's a bit unpolished, but it works. You can do:
`srec_cat dell-charger-emulator.hex -intel -o dell-charger-emulator.bin -Binary`

and theoretically edit the output binary file with a traditional hex editor. You'll want to read the manual -- the syntax is fairly non-intuitive.

There is probably a _much_ better way to do this, but I can't seem to find one. All the major hex editors I've looked at just don't seem to read this format. Apparently Okteta _(maybe)_ can, but I'm not on a KDE system and don't want to pull the entire KDE infrastructure in just for one program.

Edit 2: [python-intelhex](https://media.readthedocs.org/pdf/python-intelhex/latest/python-intelhex.pdf) library has, built in, a number of "convenience scripts" that make this easier -- including `hex2bin.py` and `bin2hex.py` -- both scripts are installed under your binary directory if you install the library on a sane (read: Unixlike) system.

The program suite seems more specialized and simple, so I think this is my official recommendation to people on how to do this, until further notice.
